name: LoaderLib
description: A general purpose file loading and handling library.
version: 0.0.1
homepage: https://github.com/FarragoFiction/LoaderLib
author: paradoxLands

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  archive: ^1.0.31
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git

dev_dependencies:
  test: ^0.12.0
