name: LoaderLib
description: A general purpose file loading and handling library.
version: 2.2.0
homepage: https://github.com/FarragoFiction/LoaderLib
author: paradoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  archive: any
  csv: any
  CommonLib:
    git:
      url: git://github.com/FarragoFiction/CommonLib.git
      ref: Dart-2.2.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: any

web:
  compiler:
    debug: dartdevc
